name: psl_eight
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  provider:
  intl:
  fluttertoast:
  flutter_screenutil:
  http:
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter_native_splash:
  background_image: "assets/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/captains/
    - assets/flags/
    - assets/squads/
    - assets/venues/



